[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@inco/lightning/=node_modules/@inco/lightning/",
  "@inco/shared/=node_modules/@inco/shared/",
  "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
  "@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/"
]
